version: "3"
services:
  backend:
    container_name: backend
    image: ${REGISTRY}/backend:${BACKEND_TAG}
    restart: always
    ports:
      - "${BACKEND_PORT:-3000}:3000"

  showcase-user-interface:
    container_name: showcase-user-interface
    image: ${REGISTRY}/showcase-user-interface:${SHOWCASE_USER_INTERFACE_TAG}
    ports:
      - "${SHOWCASE_USER_INTERFACE_PORT:-8080}:80"

  frontend-showcase-vis:
    container_name: frontend-showcase-vis
    image: ${REGISTRY}/frontend-showcase-vis:${FRONTEND_SHOWCASE_VIS_TAG}
    ports:
      - "${FRONTEND_SHOWCASE_VIS_PORT:-8081}:80"
