version: "3"
services:
  backend:
    container_name: backend
    image: ${REGISTRY}/backend:${BACKEND_TAG}
    restart: unless-stopped
    networks:
      - web

    ports:
      - "${BACKEND_PORT:-3000}:3000"

    volumes:
      - ./config:/out/config
    entrypoint: ["node", "main.js", "--provider", "${TANGLE_NODE}"]

  showcase-user-interface:
    container_name: showcase-user-interface
    image: ${REGISTRY}/showcase-user-interface:${SHOWCASE_USER_INTERFACE_TAG}
    networks:
      - web
    ports:
      - "${SHOWCASE_USER_INTERFACE_PORT:-8080}:80"

  frontend-showcase-vis:
    container_name: frontend-showcase-vis
    image: ${REGISTRY}/frontend-showcase-vis:${FRONTEND_SHOWCASE_VIS_TAG}
    ports:
      - "${FRONTEND_SHOWCASE_VIS_PORT:-8081}:80"

  map-server:
    container_name: map-server
    image: klokantech/openmaptiles-server
    ports:
      - "8084:80"
    volumes:
      - "./map-data:/data"

networks:
  web:
    external: true
