# build definition
parameters:
  appName: ''
  pool: ''


jobs:
- job: Build 
  pool: ${{ parameters.pool }}
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    workingDirectory: $(app_path)
    displayName: 'npm install and build'
  
  - task: Docker@1
    displayName: Container registry login
    inputs:
      command: login
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: canisterDocker
  
  - task: Docker@1
    displayName: Build image
    inputs:
      command: build
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: canisterDocker
      dockerFile: $(app_path)/Dockerfile
      imageName: raphaelmanke/$(app_name)
      qualifyImageName: true
  
  #- script: |
  #    docker push cloud.canister.io:5000/raphaelmanke/frontendshowcasevisulization:latest
  - task: Docker@1
    displayName: Push image
    inputs:
      command: push
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: canisterDocker
      imageName: raphaelmanke/$(app_name):latest
      qualifyImageName: true

