# build definition
parameters:
  appName: ''
  pool: ''
  npmFeed: 'FZI-IOTA-NPM'

jobs:
- job: Build 
  pool: ${{ parameters.pool }}
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '11.x'
    displayName: 'Install Node.js'
  - template: ../steps/npm.yml
  
  - template: ../steps/docker.yml
