# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  groups: dockerRegistry
  app_path: showcase-user-interface
  app_name: Showcase user-interface

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'showcase-user-interface/*'


jobs:
- template: jobs/build.yml  # Template reference
  parameters:
    app_name: $(app_name)
    pool:
      vmImage: 'ubuntu-16.04'
 